sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - 5
git:
  depth: 100000
before_script:
  - npm install -g gulp
  - gulp prod
env:
  global:
    - secure: >-
        bFXBI7IlK5qwCQimmOWF6KgRi0XsZfue0HNZhBj2SbekPtZ0QMNH/yuawnLv275G5yoK8J2U62EUcBAFQeDbL3qofmYQLMvO+xVhdVQLZwMJNmdlyKgIQPCwr9YPN8dFHsG2JNzgMFNsUCMFmcu84TbHv74f5ByOftrTXmLHqCJNwJdJdhJse/NFAlryl9A+9woo2BJAJGBugG5aT+pWpwKWg1diIh+6IM/VIjDnwiMBOePcRHVm5knFBKMWGpnSUFvisGeY1Zp44smVnogxsVt/S2M8TRmHjf5APCtdbn0nPHJtm2oWyALyy58zwHmmZPj3KhnDyH7N5G0p/r1fAu3D9nyjXYyuvsDm0jwxQ/ydRyuVR0VYLrA38TA5kxKHIuhZaHFgaNDohAYaW3mU4J4HIXEHNaxYAPg75lHzdoXB1u5pFYQqQYShdN/gcdKITQ6fAyYNFwjDp2XugATm6odI+UghrfaYLYfEK/UyKlvisnNHJTUYFNJZekt7sw1agazPrvlr5cUIRiQOPHdafgtWGvgkqtkKO6kDDAb/+MB7+hVolRJMJAMXzuV+vPrAb8Njk+ezJ0KLm8teEH5RdMlgMN3/i5C42bZwlLGQuXbuOkKm6X0CrsuqQby9SRWvWZvmKlaTSnO2zWGTDoPxzTxFGxhimFZfxRo6oP+TVqc=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/lefjor/lefjor.github.io.git
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
  'on':
    branch: master
