sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - 5
git:
  depth: 100000
before_script:
  - gulp build --env=prod
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
  'on':
    branch: master
